# Numpy

# create an array

In [1]:
import numpy as np

In [2]:
simple_list=[2,3,4]
np.array(simple_list)

array([2, 3, 4])

In [3]:
arr=np.array([5,7,8])
arr

array([5, 7, 8])

In [4]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,28)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27])

In [6]:
np.arange(5,35,6)

array([ 5, 11, 17, 23, 29])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [9]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [11]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [13]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [14]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [15]:
np.random.rand(2,4)

array([[0.75521998, 0.60693786, 0.94831021, 0.33204909],
       [0.5440293 , 0.92006559, 0.64577695, 0.83895629]])

In [16]:
np.random.randn(2,4)

array([[ 0.83263595, -0.67021475, -1.86523117,  0.06582482],
       [ 0.14523715, -0.3491256 , -0.46971069,  1.34631242]])

In [17]:
np.random.rand(2,5)

array([[0.71584334, 0.11522142, 0.98352583, 0.49378564, 0.88188908],
       [0.04014254, 0.78771788, 0.23608645, 0.09626097, 0.45797604]])

In [18]:
np.random.randint(0,10,15)

array([7, 2, 9, 5, 8, 3, 6, 5, 2, 9, 9, 2, 7, 3, 6])

In [19]:
np.random.randint(20,56,100)

array([25, 43, 42, 45, 47, 38, 43, 37, 44, 45, 24, 20, 53, 40, 42, 30, 48,
       36, 28, 36, 26, 32, 26, 24, 55, 44, 48, 30, 21, 48, 50, 32, 50, 47,
       47, 24, 36, 40, 48, 55, 36, 32, 27, 31, 29, 47, 33, 31, 26, 26, 49,
       53, 55, 47, 50, 53, 43, 44, 21, 28, 54, 22, 53, 36, 51, 47, 24, 36,
       20, 30, 48, 40, 24, 39, 42, 37, 33, 30, 28, 24, 21, 35, 38, 46, 43,
       53, 32, 50, 33, 42, 20, 20, 31, 52, 27, 28, 47, 41, 36, 42])

In [20]:
np.random.randint(20,56,100)

array([47, 51, 50, 46, 27, 55, 31, 34, 45, 46, 32, 30, 23, 53, 48, 26, 53,
       20, 22, 37, 26, 23, 20, 40, 50, 38, 21, 53, 29, 43, 44, 49, 29, 20,
       42, 54, 43, 27, 44, 23, 47, 27, 24, 54, 28, 53, 47, 24, 42, 42, 31,
       20, 26, 28, 44, 39, 52, 37, 55, 27, 54, 22, 32, 20, 38, 41, 22, 37,
       41, 32, 35, 38, 36, 39, 50, 36, 34, 48, 24, 51, 55, 31, 39, 31, 45,
       52, 32, 42, 25, 49, 26, 22, 51, 49, 41, 29, 37, 49, 52, 48])

In [21]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
rand_array=np.random.randint(0,10,5)
rand_array

array([2, 9, 5, 6, 7])

In [23]:
sample_array.argmin()

0

In [24]:
rand_array.argmin()

0

In [25]:
rand_array.max()

9

In [26]:
sample_array.min()

2

In [27]:
rand_array.argmax()

1

In [28]:
sample_array.argmax()

17

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [33]:
sample_array=sample_array.reshape(2,9)
sample_array

array([[10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [34]:
sample_array=sample_array.reshape(3,4)
sample_array

ValueError: cannot reshape array of size 18 into shape (3,4)

In [ ]:
sample_array[1]=100
sample_array

In [ ]:
sample_array=np.arange(10,100)
sample_array

In [ ]:
sample_array[1:12]

In [35]:
sample_array[:]=1001
sample_array

array([[1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001],
       [1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001]])

# Two-Dimensional array

In [ ]:
import numpy as np

In [ ]:
sample_matrix=np.array(([21,13,2,15],[15,2,54,65],[56,76,24,7]))
sample_matrix

In [ ]:
sample_matrix[2][2]

In [ ]:
sample_matrix[1][2]

In [ ]:
sample_matrix[:,2]

In [ ]:
sample_matrix[1,1]

In [ ]:
sample_matrix[1:3,2:4]

In [ ]:
sample_matrix[1:,2:]

In [ ]:
sample_matrix[2]

# Pandas

In [1]:
import pandas as pd

In [2]:
labels=['a','b','c','d']

In [3]:
list=[10,20,38,40]

In [4]:
import numpy as np

In [5]:
array=np.array([1,2,3,4])

In [7]:
dict={'w':10,'x':20,'y':30,'z':40}

In [8]:
pd.Series(data=list)

0    10
1    20
2    38
3    40
dtype: int64

In [9]:
pd.Series(data=list,index=labels)

a    10
b    20
c    38
d    40
dtype: int64

In [10]:
pd.Series(labels,list)

10    a
20    b
38    c
40    d
dtype: object

In [11]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

# Pandas Dataframe and Indexing

In [12]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [13]:
sports1['basketball']

3

In [14]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [15]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [18]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.598430  0.203180  0.605469  0.979245  0.242468
B  0.871359  0.572849  0.675962  0.212282  0.082555
C  0.465798  0.799011  0.645066  0.722934  0.405058
D  0.841206  0.571713  0.361300  0.280473  0.641705
E  0.943390  0.745308  0.151005  0.951462  0.249458
F  0.668108  0.641519  0.996323  0.625323  0.133343
G  0.105319  0.477577  0.069682  0.417584  0.181837
H  0.057303  0.391236  0.593398  0.257260  0.356684

In [19]:
df1[['Score2','Score1','Score5']]

Score2    Score1    Score5
A  0.203180  0.598430  0.242468
B  0.572849  0.871359  0.082555
C  0.799011  0.465798  0.405058
D  0.571713  0.841206  0.641705
E  0.745308  0.943390  0.249458
F  0.641519  0.668108  0.133343
G  0.477577  0.105319  0.181837
H  0.391236  0.057303  0.356684

In [21]:
df1['Score6']=df1['Score1']-df1['Score2']
df1

Score1    Score2    Score3    Score4    Score5    Score6
A  0.598430  0.203180  0.605469  0.979245  0.242468  0.395250
B  0.871359  0.572849  0.675962  0.212282  0.082555  0.298511
C  0.465798  0.799011  0.645066  0.722934  0.405058 -0.333212
D  0.841206  0.571713  0.361300  0.280473  0.641705  0.269494
E  0.943390  0.745308  0.151005  0.951462  0.249458  0.198082
F  0.668108  0.641519  0.996323  0.625323  0.133343  0.026589
G  0.105319  0.477577  0.069682  0.417584  0.181837 -0.372257
H  0.057303  0.391236  0.593398  0.257260  0.356684 -0.333932

In [22]:
df1.drop('Score5',axis=1)

Score1    Score2    Score3    Score4    Score6
A  0.598430  0.203180  0.605469  0.979245  0.395250
B  0.871359  0.572849  0.675962  0.212282  0.298511
C  0.465798  0.799011  0.645066  0.722934 -0.333212
D  0.841206  0.571713  0.361300  0.280473  0.269494
E  0.943390  0.745308  0.151005  0.951462  0.198082
F  0.668108  0.641519  0.996323  0.625323  0.026589
G  0.105319  0.477577  0.069682  0.417584 -0.372257
H  0.057303  0.391236  0.593398  0.257260 -0.333932

In [23]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.598430  0.203180  0.605469  0.979245  0.242468  0.395250
B  0.871359  0.572849  0.675962  0.212282  0.082555  0.298511
C  0.465798  0.799011  0.645066  0.722934  0.405058 -0.333212
D  0.841206  0.571713  0.361300  0.280473  0.641705  0.269494
F  0.668108  0.641519  0.996323  0.625323  0.133343  0.026589
G  0.105319  0.477577  0.069682  0.417584  0.181837 -0.372257
H  0.057303  0.391236  0.593398  0.257260  0.356684 -0.333932

In [29]:
df2={'ID':[101,102,103,104,105],'Name':['john','mercy','akash','kavin','lala'],'Profit':['20','30','40','50','60']}
df=pd.DataFrame(df2)
df

ID   Name Profit
0  101   john     20
1  102  mercy     30
2  103  akash     40
3  104  kavin     50
4  105   lala     60

## Assessment
1. Create a null vector of size 10
2. Create a null vector of size 10 but the fifth value should be one
3. Create a vector with values ranging from 10 to 65
4. Reverse a above vector
5. Create a 3x3 matrix with values ranging from 0 to 8

In [30]:
import numpy as np

In [34]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
a=np.zeros(10)
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [41]:
z=np.arange(10,66)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65])

In [42]:
z[::-1]

array([65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [44]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
